#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh
nm-applet &
pamac-tray &
picom -CG &
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/gnome-keyring-daemon --start --components=secrets &
/usr/bin/dunst &
nitrogen --restore &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4
bspc config focused_border_color "#ffb52a"
bspc config normal_border_color "#444"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Google-chrome desktop='^2' follow=on focus=on
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a Tilix desktop='^1' follow=on
bscp rule -a Spotify desktop='^6' follow=on
bspc rule -a Lollypop desktop='^4' follow=on
bspc rule -a Org.gnome.Nautilus desktop='^3' follow=on
bspc rule -a Sublime_text desktop='^8' follow=on
bspc rule -a Typora desktop='^7' follow=on
bspc rule -a Pamac-manager desktop='^5' follow=on